artifact_uri: file:///home/mle-user/mle-mlflow/mlflow_experiments_store/0/3883327c30ff429ea0be841c4fbfc910/artifacts
end_time: 1740382170353
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 3883327c30ff429ea0be841c4fbfc910
run_name: Default
run_uuid: 3883327c30ff429ea0be841c4fbfc910
source_name: ''
source_type: 4
source_version: ''
start_time: 1740382170278
status: 3
tags: []
user_id: mle-user
