artifact_uri: file:///home/mle-user/mle-mlflow/mlflow_experiments_store/0/19cb1d756e014902bedde6be5bf4433c/artifacts
end_time: 1740381846803
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: 19cb1d756e014902bedde6be5bf4433c
run_name: Default
run_uuid: 19cb1d756e014902bedde6be5bf4433c
source_name: ''
source_type: 4
source_version: ''
start_time: 1740381846784
status: 3
tags: []
user_id: mle-user
