artifact_uri: file:///home/mle-user/mle-mlflow/mlflow_experiments_store/0/dc72d9b1f9d0442f86854439e420ec04/artifacts
end_time: 1740381727469
entry_point_name: ''
experiment_id: '0'
lifecycle_stage: active
run_id: dc72d9b1f9d0442f86854439e420ec04
run_name: Default
run_uuid: dc72d9b1f9d0442f86854439e420ec04
source_name: ''
source_type: 4
source_version: ''
start_time: 1740381727452
status: 4
tags: []
user_id: mle-user
